name: axon_vision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- NETWORK & STORAGE ---
  http: ^1.2.0
  get_storage: ^2.1.1

  # --- STATE MANAGEMENT & NAVIGATION ---
  get: ^4.7.2
  go_router: ^13.0.0

  # --- UI & FONTS ---
  google_fonts: ^6.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.0

  # --- WIDGETS TAMBAHAN ---
  calendar_date_picker2: ^2.0.1
  month_year_picker: ^0.5.0+1
  syncfusion_flutter_datagrid: ^31.2.3

  # --- FILE & MEDIA ---
  image_picker: ^1.2.1
  file_picker: ^10.3.8

  # --- WEB VIEW ---
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3
  pointer_interceptor: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/